### ISSUE TITLE
1 byte matches

### ISSUE THREAD

**Issue by bboxy** [dmsc/zx02#2]
Hi,

As another match can follow a match, in case of matches it should be okay to split the matches into chunks of 256 bytes to avoid 16 bit lengths. As for literals it would even be sufficient to check only for an extra condition if the literal was 256 bytes big. Then an additional type bit(s) is needed to decide whether another literal will follow up (as it is a long run) or we continue with rep/match? This would avoid the use of 1 byte matches?

Greetz,

Toby aka bitbreaker

**Comment by dmsc** [comment]
Hi!

Yes, what the encode currently does is to split matches of more than 256 bytes - but after a match you can't have a repeated-match, so you have to include the full offset again.

After a literal, it is not easy to add a bit to decide if a new literal follows, as the decoder always reads bits in pairs, so that the byte boundaries always fall in the elias significant bit - makes the code smaller and faster.

If you want to try measuring the increased compression with those changes, you can modify the parameters in the encoder and  try with sample inputs.
